version: "3"

services:
  siri-gpt:
    image: siri-gpt
    environment:
      - API_KEY=$API_KEY
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - PROXY_URL=$PROXY_URL
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=6379
      - MAX_TOKEN_LIMIT=4000
    ports:
      - 5000:5000
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379